name = "ahmmd"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "build/worker.js"

# Bundle settings for Cloudflare Pages
[build.upload.rules]
[[build.upload.rules]]
type = "ESModule"
glob = "**/*.js"

# Disable minification as it's handled by Vite
[build]
minify = false

# Environment variables (these should be set in Cloudflare Pages dashboard)
[vars]
NODE_ENV = "production"
