name = "ahmmd"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "build/worker.js"

# Bundle settings to properly handle AWS SDK
[build.upload.rules]
[[build.upload.rules]]
type = "ESModule"
glob = "**/*.js"
